sudo: required
services: docker

script:
    - SCRIPT=run_build_image.sh
    - curl -O https://raw.githubusercontent.com/cyber-dojo-languages/image_builder/master/${SCRIPT}
    - chmod +x ./${SCRIPT}

    - REPO_URL=https://github.com/${TRAVIS_REPO_SLUG}
    - echo "PASSING ARG=:${REPO_URL}:"
    - ./${SCRIPT} ${REPO_URL}

    # push image (which is _not_ name based on TRAVIS_REPO_SLUG) to dockerhub
    - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
    - docker push cyberdojofoundation/elm-0.18.0
